# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5
loom_version=1.7.4

# Mod Properties
version=1.0.0
group=com.example

# Dependencies
fabric_api_version=0.104.0+1.21.1
modmenu_version=11.0.2
cloth_config_version=15.0.127
